### ISSUE TITLE
DOT named server names are converted into list of servers to connect to

### ISSUE THREAD

**Issue by m-tyler** [NielsLiisberg/vscode-ibm-i-run-sql-with-acs#5]
We use a server name of IBMi.office.company.local, when I attempt to open ACS the extension asks me which server and it gives me a list like

```
IBMi
office
company
local
```
The README indicates it only looks for commas to separate the names.

**Comment by NielsLiisberg** [comment]
Hello Winco

We can reproduce the issue here. We have fixed it, and will push a new
release real soon.

fre. 19. aug. 2022 kl. 17.47 skrev Winco ***@***.***>:

**Comment by m-tyler** [comment]
👍
👍

**Comment by m-tyler** [comment]
Updated and its working!

**Comment by NielsLiisberg** [comment]
Perfect !! Thanx for the feedback
